data:
    name: 'coco'
    labels: outputs/magic-point_cocoevent-export1  # Complete with your export labels
    cache_in_memory: false
    validation_size: 192
    augmentation:
        photometric:
            enable: true
            primitives: ['additive_speckle_noise','motion_blur']
            params:
                additive_speckle_noise: {prob_range: [0, 0.0035]} #二值 red or blue
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57
                allow_artifacts: true
            valid_border_margin: 3
model:
    name: 'magic_point'
    batch_size: 32
    eval_batch_size: 32
    learning_rate: 0.001
    detection_threshold: 0.001 # 0.015
    nms: 4
    # top_k: 300
train_iter: 18000
validation_interval: 1000
save_as_pb: false
