data:
    name: 'coco'
    cache_in_memory: false
    validation_size: 96
    labels: outputs/magic-point_coco-export1  # use your own labels here
    augmentation:
        photometric:
            enable: true
            primitives: ['random_contrast', 'additive_speckle_noise',
                         'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                salt_pepper_noise: 
                    salt_vs_pepper: 0.2
                    amount: 0.004
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3
model:
    name: 'super_point'
    batch_size: 2
    eval_batch_size: 2
    learning_rate: 0.0001
    lambda_d: 0.05
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 10000
    detection_threshold: 0.001
    nms: 2 # if the size of image transfer (H/8,W/8,C) into (H/16,W/16,C), the nms change into 2
    # top_k: 600
train_iter: 600000
validation_interval: 5000
save_as_pb: false #Save output as .pb if true, ckpt if false
