data:
    name: 'coco'
    cache_in_memory: false
    validation_size: 96
    labels: outputs/magic-point_cocoevent-export1 # use your own labels here
    augmentation:
        photometric:
            enable: true
            primitives: ['additive_speckle_noise','motion_blur']
            params:
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3
model:
    name: 'super_point'
    batch_size: 2
    eval_batch_size: 2
    learning_rate: 0.0001
    lambda_d: 0.05
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 10000
    detection_threshold: 0.001
    nms: 4
    # top_k: 600
train_iter: 600000
validation_interval: 5000
save_as_pb: False #Save output as .pb if true, ckpt if false